version: '3.4'

services:

  wordpress:
    depends_on:
      - my_sql_db
    image: wordpress:4.9.0
    hostname: my.site.com
    restart: always
    volumes:
      - wp-content:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: my_sql_db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
      VIRTUAL_HOST: rac021.com
      LETSENCRYPT_HOST: rac021.com
      LETSENCRYPT_EMAIL: r.yahiaoui.21@gmail.com
    ports:
      - 8080:80
      - 443:443
    networks:
      - backend_network
      
  my_sql_db:
    image: mysql:8.0.0
    restart: always
    volumes:
       - my_sql_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - backend_network
      
  phpmyadmin:
    depends_on:
      - my_sql_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: my_sql_db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - backend_network
      
networks:
  backend_network:
  
volumes:
  my_sql_db_data:
  wp-content:
